[package]
name = "rcgenmsg"
version = "0.1.0"
authors = ["Fan Jiang <prof.fan@foxmail.com>"]

[dependencies]
pest = "^1.0"
pest_derive = "^1.0"

argparse = "0.2.1"
handlebars = "1.0.0-beta.2"

serde_derive = "^1.0"
serde_json = "^1.0.22"

serde = "^1.0.69"

Inflector = "*"