# Automatically generated by rcgenmsg for test_messages/std_msgs/Header.msg
@0x9ff5ad36ee569495;


using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("ros::std_msgs");


struct Header {
seq @0 : UInt32;
stamp @1 : UInt64;
frameId @2 : Text;
}
